/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "twefwdiwaiwczutlkjvw"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3ZWZ3ZGl3YWl3Y3p1dGxranZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI3ODA1NDAsImV4cCI6MjA3ODM1NjU0MH0.2f4lrRCBz7j1fmGFbyf_RS_kgQ-yq-v_U1X7I4xkH5A"